import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Stack, Text } from "@chakra-ui/react";
import Quiz from "@/components/Quiz";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Martynui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        bg="gray.700"
        minH="100vh"
        color="gray.100"
        w="full"
        justify="center"
        align="center"
        p="8"
        backgroundImage="url('/assets/tattoo.jpg')"
        backgroundPosition="center"
        backgroundRepeat="no-repeat"
        backgroundBlendMode="multiply"
      >
        <Text fontSize="4xl">MARTYNAI</Text>
        <Text fontSize="sm" color="gray.300">
          Ar pavyks išspręsti šį klausimyną?
        </Text>
        <Quiz />
      </Stack>
    </>
  );
}
